# Dependencies should be same as in ``requirements/package.txt``
# Install env with command:
# conda env create python3.x -n name3x -f environment.yml

channels:
    - conda-forge
dependencies:
    - numpy
    - numba
    - jupyter
    pip:
      - sphinx
      - sphinx-rtd-theme
      - pytest
      - hypothesis
