# Python dependensies to run the code.
#
# Install miniconda with shell script inside buildscripts/ using:
#
#   ./buildscripts/install_miniconda.sh
#
# Export path to the miniconda distribution:
#
#   export PATH=~/miniconda3/bin:$PATH
#
# Install conda environment with:
#
#   conda env create python3.x -n name3x -f environment.yml

channels:
    - conda-forge
dependencies:
    - numpy
    - scipy
    - numba
    - jupyter
    - matplotlib
    - line_profiler
    - memory_profiler
    pip:
      - sphinx
      - sphinx-rtd-theme
      - ghp-import
      - pytest
      - hypothesis
